# Generated by Django 2.2.6 on 2021-09-04 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20210903_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',), 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
