# Generated by Django 2.2.6 on 2021-09-04 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20210904_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',), 'permissions': (('can_read_this', 'permission for post'),)},
        ),
    ]
